# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170731_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='applycost',
            field=models.CharField(default='0', max_length=8, verbose_name='\u8acb\u6b3e\u91d1\u984d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='\u4e8b\u7531'),
        ),
        migrations.AlterField(
            model_name='article',
            name='filldate',
            field=models.CharField(default='00000000', max_length=8, verbose_name='\u586b\u5beb\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='\u8cfc\u8cb7\u54c1\u9805'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uid',
            field=models.CharField(default='0', max_length=10, verbose_name='\u5b78\u865f'),
        ),
    ]
