# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170731_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filldate',
            field=models.CharField(default='00000000', max_length=8, verbose_name='\u586b\u5beb\u65e5\u671fYYYYMMDD'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='\u8cfc\u8cb7\u54c1\u9805(EX: \u8607\u6253\u9905X1)'),
        ),
    ]
