# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170731_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filldate',
            field=models.DateTimeField(verbose_name='\u586b\u5beb\u65e5\u671fYYYYMMDD'),
        ),
    ]
