# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170731_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filldate',
            field=models.DateField(verbose_name='\u586b\u5beb\u65e5\u671fYYYYMMDD'),
        ),
    ]
