# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20170731_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filldate',
            field=models.DateField(auto_now_add=True, verbose_name='Date YYYY-MM-DD'),
        ),
    ]
