# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20170731_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filldate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date YYYY-MM-DD'),
        ),
    ]
