# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20170805_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.FileField(default='/uploads/anonymous.png', upload_to='uploads/', verbose_name='\u767c\u7968\u4e0a\u50b3'),
        ),
    ]
